---
title: "Chapter 4. Application of Numerical Methods to Model Equations"
---

# Inviscid Burgers' Equation

The Burgers’ equation serves as an analog to the Navier Stokes equations. The equation includes an unsteady term, a nonlinear convection term, and a viscous term.

$$
\frac {\partial u}{\partial t}+u\frac {\partial u}{\partial x}=\mu\frac {\partial^2u}{\partial x^2}
$$ {#eq-burgers}

When the viscous term is included, Eqn. (@eq-burgers) is parabolic. The inviscid Burgers' equation arises when viscous effects are zero, $\mu=0$.

$$
\frac {\partial u}{\partial t}+u\frac {\partial u}{\partial x}=0
$$ {#eq-inviscid-burgers}

Whereas the linear 1D convection equation models the simple case of a wave propagating at a constant speed, Eqn. (@eq-inviscid-burgers) may be viewed as a nonlinear wave equation that can model waves propagating at varying speeds. Since Burgers' equation can correctly model varying wave speeds, it can be used to model shocks as waves of differing speeds coalesce. This wave equation is similarly hyperbolic.

Nonlinear hyperbolic PDEs exhibit two types of solutions according to Lax (1954). Consider the general case of the equation below. The Jacobian $A=\frac {\partial F_i}{\partial u_j}$ is introduced from the chain rule. If $u$ and $F$ are both vectors, $A$ is a matrix.

$$
\frac {\partial u}{\partial t}+\frac {\partial F}{\partial x}=\frac {\partial u}{\partial t}+A\frac {\partial u}{\partial x}=0
$$ {#eq-general-hyperbolic-pde}

## Lax Method

First order methods are rarely used in solving hyperbolic equations owing to their dissipative nature. The Lax method is typically used to demonstrate its dissipative nature and the application of a first order method to a nonlinear equation.

$$
u_j^{n+1}=\frac {u_{j-1}^n+u_{j+1}^n}2-\frac {\Delta t}{\Delta x}\frac {F_{j+1}^n-F_{j-1}^n}2
$$ {#eq-lax-method-inviscid-burgers}

The first term is $u_j^n$ averaged between its neighboring cells. This introduces artificial viscosity into the method that smooths out any instabilities or oscillations in the solution.

::: {.callout-note title="Derivation of the Lax Method" collapse="true"}
Expand $u_j^{n+1}$ about $u_j^n$ using a Taylor series and substitute the time derivative term with the spatial derivative. From Eqn. (@eq-general-hyperbolic-pde), we have that $u_t=-F_x$. Therefore

$$
\begin{aligned}
u(x,t+\Delta t) & =u(x,t)+\left.\frac {\partial u}{\partial t}\right|_{x,t}\Delta t+\left.\frac {\partial^2u}{\partial t^2}\right|_{x,t}\frac {\Delta t^2}{2!}+\cdots \\
 & =u(x, t)-\left.\frac {\partial F}{\partial x}\right|_{x,t}\Delta t+\mathcal O(\Delta t^2)
\end{aligned}
$$

Neglecting the higher order terms and applying a central difference scheme on $F_x$, the Lax method is obtained. An average is used for calculating the $u_j^n$ term to introduce numerical dissipation.

$$u_j^{n+1}=u_j^n-\frac {\Delta t}{\Delta x}\frac {F_{j+1}^n-F_{j-1}^n}2$$
:::

The amplification factor for this scheme is given below

$$
G=\cos\beta-i\frac {\Delta t}{\Delta x}A\sin\beta
$$ {#eq-lax-method-inviscid-burgers-amplification-factor}

where the dimensionless wave number $\beta$ is $k\Delta x$. For Burgers' equation, $F=u^2/2$, so the Jacobian is simply $A(u)=u$. Stability occurs when $|G|\leq1$. For the $G$ above, Eqn. (@eq-lax-method-inviscid-burgers-amplification-factor) reduces down to

$$
\left|\frac {\Delta t}{\Delta x}u_{\mathrm{max}}\right|\leq1
$$

where $u_{\mathrm{max}}$ is the maximum eigenvalue of the Jacobian $A$.

## Lax-Wendroff Method

The Lax-Wendroff method was one of the first second order finite difference methods derived for hyperbolic PDEs. Once again, consider the general form of the governing Eqn. (@eq-general-hyperbolic-pde). The Lax-Wendroff method is

$$
u_j^{n+1}=u_j^n-\frac {\Delta t}{\Delta x}\frac {F_{j+1}^n-F_{j-1}^n}2+\frac 12\left(\frac {\Delta t}{\Delta x}\right)^2\left[A_{j+\frac 12}^n\left(F_{j+1}^n-F_j^n\right)-A_{j-\frac 12}^n\left(F_j^n-F_{j-1}^n\right)\right]
$$ {#eq-lax-wendroff-method-inviscid-burgers}

There are many different ways of evaluating the Jacobian matrix at the half interval $j\pm\frac 12$. The simplest is to use the average of the neighboring cell values. With Burgers' equation, $A(u)=u$ and the half interval Jacobians can be evaluated as

$$
A_{j\pm\frac 12}=A\left(\frac {u_j+u_{j\pm1}}2\right)=\frac {u_j+u_{j\pm1}}2
$$

::: {.callout-note title="Derivation of the Lax-Wendroff Method" collapse="true"}
Start off in the same manner as the Lax method and expand $u_j^{n+1}$ about $u_j^n$ using a Taylor series.

$$
u(x,t+\Delta t)=u(x,t)+\left.\frac {\partial u}{\partial t}\right|_{x,t}\Delta t+\left.\frac {\partial^2u}{\partial t^2}\right|_{x,t}\frac {\Delta t^2}{2!}+\left.\frac {\partial^3u}{\partial t^3}\right|_{x,t}\frac {\Delta t^3}{3!}+\cdots
$$

Next, replace the time derivatives with spatial derivatives. From Eqn. (@eq-general-hyperbolic-pde), the first time derivative is

$$
\frac {\partial u}{\partial t}=-\frac {\partial F}{\partial x}
$$

For the second derivative term, differentiate the equation above with respect to time and interchange the differentiation order.

$$
\frac {\partial^2u}{\partial t^2}=-\frac {\partial}{\partial x}\frac {\partial F}{\partial t}=-\frac {\partial}{\partial x}\frac {\partial F}{\partial u}\frac {\partial u}{\partial t}=\frac {\partial}{\partial x}\left(A\frac {\partial F}{\partial x}\right)
$$

The last step is due to the chain rule. Substitute into the Taylor series to obtain

$$
u(x,t+\Delta t)=u(x,t)-\left.\frac {\partial F}{\partial x}\right|_{x,t}\Delta t+\left.\frac {\partial}{\partial x}\left(A\frac {\partial F}{\partial x}\right)\right|_{x,t}\frac {\Delta t^2}2+\mathcal O(\Delta t^3)
$$

Apply central differencing schemes to all derivative terms. The second order derivative is

$$
\begin{aligned}
\frac {\partial}{\partial x}\left(A\frac {\partial F}{\partial x}\right) & \approx\frac 1{\Delta x}\left[A_{j+\frac 12}\left.\frac {\partial F}{\partial x}\right|_{j+\frac 12}-A_{j-\frac 12}\left.\frac {\partial F}{\partial x}\right|_{j-\frac 12}\right] \\ & =\frac 1{\Delta x}\left[A_{j+\frac 12}\frac {F_{j+1}-F_j}{\Delta x}-A_{j-\frac 12}\frac {F_j-F_{j-1}}{\Delta x}\right] \\ & =\frac 1{\Delta x^2}\left[A_{j+\frac 12}\left(F_{j+1}-F_j\right)-A_{j-\frac 12}\left(F_j-F_{j-1}\right)\right]
\end{aligned}
$$

The $F_x$ terms, when evaluated at the cell interface, actually utilize a central difference as $F_j$ and $F_{j\pm1}$ are both exactly $\frac {\Delta x}2$ away from the boundary. Therefore, central differences are used to decompose all derivative terms into their stencil approximations and the second order accuracy is maintained. Putting everything together gives the Lax-Wendroff method.
:::

The amplification factor is

$$
G=1-2\left(\frac {\Delta t}{\Delta x}A\right)^2(1-\cos\beta)-2i\frac {\Delta t}{\Delta x}A\sin\beta
$$ {#eq-lax-wendroff-method-inviscid-burgers-amplification-factor}

When $|G|\leq1$, the scheme is stable. For the amplification above, this simplifies down to

$$
\left|\frac {\Delta t}{\Delta x}u_{\mathrm{max}}\right|\leq1
$$ {#eq-lax-wendroff-method-inviscid-burgers-stability}

When Lax-Wendroff is applied to the example problem, the method correctly predicts the position of the discontinuity. Moreover, the solution is relatively sharp and well-defined, with some oscillations occurring at either ends of the discontinuity. In comparison, the Lax method was purely monotone and did not exhibit any oscillatory motion due to the method's lower order accuracy. When the Courant number is decreased, the number of oscillations in the Lax-Wendroff solution increases as the solution quality is degraded.

The numerical flux is

$$
f_{j+\frac 12}=\frac {F_{j+1}+F_j}2-\frac 12\frac {\Delta t}{\Delta x}\lambda_{j+\frac 12}^2\left(u_{j+1}-u_j\right)
$$ {#eq-lax-wendroff-method-inviscid-burgers-numerical-flux}

where $\lambda_{j+\frac 12}$ is the eigenvalue of the Jacobian $A_{j+\frac 12}$. For Burgers' equation, this is simply $u_{j+\frac 12}$. When compared to that of the Lax method, the difference is the correction term below.

$$
f_{j+\frac 12}^{\mathrm{LW}}-f_{j+\frac 12}^{\mathrm L}=\frac {\Delta x}{\Delta t}\frac {u_{j+1}-u_j}2\left[1-\left(\lambda_{j+\frac 12}\frac {\Delta t}{\Delta x}\right)^2\right]
$$

This correction term can be added to $f_{j+\frac 12}^{\mathrm L}$ to provide second order accuracy and modify the solution to the form of Lax-Wendroff. However, due to the higher order, oscillations may occur near discontinuities. To avoid this, it is desired to suppress this correction term near discontinuities. This is done through the use of **limiters**.

$$
f_{j+\frac 12}^{\mathrm L}=\frac 12\left[F_j+F_{j-1}-\frac {\Delta x}{\Delta t}\left(u_{j+1}-u_j\right)\right]+\phi\frac {\Delta x}{\Delta t}\frac {u_{j+1}-u_j}2\left[1-\left(\lambda_{j+\frac 12}\frac {\Delta t}{\Delta x}\right)^2\right]
$$

The function $\phi$ limits the presence of the correction term near discontinuities to reduce the Lax method's overall order and achieve a monotone, or near-monotone, behavior locally. More information is given about limiters in Section 4.4.12.

## MacCormack Method

This is the two-step predictor-corrector version of Lax-Wendroff. The Jacobian becomes computationally difficult and expensive for nonlinear equations in Lax-Wendroff. MacCormack avoids evaluating the Jacobian entirely and is therefore, more easily implemented for highly nonlinear problems.

$$
\begin{aligned}
u_j^{\overline{n+1}} & =u_j-\frac {\Delta t}{\Delta x}\left(F_{j+1}^n-F_j^n\right) \\
u_j^{n+1} & =\frac 12\left[u_j^n+u_j^{\overline{n+1}}-\frac {\Delta t}{\Delta x}\left(F_j^{\overline{n+1}}-F_{j-1}^{\overline{n+1}}\right)\right]
\end{aligned}
$$ {#eq-maccormack-method-inviscid-burgers}

The amplification factor, Eqn. (@eq-lax-wendroff-method-inviscid-burgers-amplification-factor), and stability requirement, Eqn. (@eq-lax-wendroff-method-inviscid-burgers-stability), are the same as that of Lax-Wendroff. When compared to Lax-Wendroff for the example problem, the two solutions differ. This is due to the switched differencing in the predictor and corrector steps, as well as the nonlinear nature of the PDE. In general, MacCormack provides better resolution at discontinuities. For the best resolution, the difference in the predictor, $F_{j+1}-F_j$, should be in the same direction as the propagation direction of the discontinuity. If the wave is propagating to the left, then the difference should be $F_{j-1}-F_j$ instead.

## Godunov Scheme



