---
title: Chapter 7. Turbulent and Transitional Internal Flow
# format:
#     pdf:
#         toc: true
#         colorlinks: true
---

# Introduction

With external flows, the freestream conditions were unaffected by the boundaries. With internal flows, however, due to their confined nature, the wall may have a significant impact on the mean flow behavior. Taking fully developed turbulent flow through a smooth pipe as an example, the flow field can be divided into three sublayers. The layer closest to the wall is the *viscous sublayer* and typically is defined as the region between $0\leq y^+\leq5$. The *buffer zone* or *transition layer* extends beyond this, between $5\leq y^+\leq30$. The *outer layer* occupies the rest of the flow field. Close to the wall, the effect of wall curvature is small, so the fluid is "unaware" that the flow field is confined on all sides. Similarly, the buffer zone is also marginally affected by the macroscopic flow field. Only the outer layer, where turbulence is largely present, does the physics of internal flows differ depending on the characteristics of the flow field. The following correlations for dimensionless velocity, $u^+$, have been developed.

$$
\begin{aligned}
u^+ & =y^+ &&& 0\leq y^+ & \leq5 \\
u^+ & =5.0\ln y^+-3.05 && \phantom{00000} & 5\leq y^+ & \leq30 \\
u^+ & =\frac 1{\kappa}\ln y^++B &&& 30\leq y^+ & \leq200
\end{aligned}
$$

where $\kappa=0.4$ and $B=5.0$.

## Laminar-Turbulent Flow Transition

There are three regimes that can be distinctly defined: laminar, transition, and fully turbulent. The transition point between laminar and turbulent flows is sensitive to a multitude of parameters, most notably duct geometry, surface roughness, and the presence of any flow disturbances. The Reynolds number is the most improtant parameter in characterizing this transition process.

::: {.callout-note}
The characteristic length used for the Reynolds number should be related to the duct cross-sectional length. For a circular pipe, this would be the inner diameter. For non-circular geometries, this would be the hydraulic diameter, $D_H$, or in certain cases, the square root of the cross-sectional area.
:::

Surface roughness and presence of disturbances all serve to lower the critical $\mathrm{Re}_D$ that marks transition. Though laminar flows have been maintained up to $\mathrm{Re}_D\simeq10^5$ in ideal conditions, it is generally assumed that the flow remains laminar if $\mathrm{Re}_D\leq2100$ and fully turbulent if $\mathrm{Re}_D>10^4$. The transition flow regime occurs for $2100<\mathrm{Re}_D\leq10^4$.

The effect of surface roughness on an internal flow field is similar to that explained in Chapter 6. For $\varepsilon_s^+\leq5$, the roughness is fully submerged in the viscous sublayer, so the duct is considered *hydraulically smooth* and roughness has virtually no effect on friction. The skin friction coefficient $C_f$ is only a function of the Reynolds number, $\mathrm{Re}_D$. For $\varepsilon_s^+>70$, the surface is *fully rough* and protrudes past the viscous sublayer. The roughness has an overwhelming effect on the wall shear stress so $C_f$ is only a function of $\varepsilon_s^+$ and independent of $\mathrm{Re}_D$. For $5<\varepsilon_s^+\leq70$, the surface is *transitionally rough* and the skin friction coefficient is a function of both $\varepsilon_s^+$ and $\mathrm{Re}_D$. Surface roughness affects heat and mass transfer primarily by increasing the total interfacial area between the fluid and wall, thereby promoting local mixing of the fluid. As a result, rougher surfaces increase the local friction factor as well as heat and mass transfer coefficients. Norris (1970) suggested the empirical correlation for Nusselt number of a rough surface.

$$
\frac {\mathrm{Nu}_{D_H}}{\mathrm{Nu}_{D_H,\mathrm{smooth}}}=\min\left[4^n, \left(\frac {C_f}{C_{f,\mathrm{smooth}}}\right)^n\right]
$$ {#eq-norris-1970-rough-nusselt}

where empirical constant $n$ is determined using

$$
\begin{aligned}
n & =0.68\mathrm{Pr}^{0.215} && \phantom{00000} & \mathrm{Pr} & <6 \\
n & =1 &&& \mathrm{Pr} & >6
\end{aligned}
$$ {#eq-norris-1970-rough-nusselt-n}

## Development of Temperature and Concentration Profiles

The entrance length is defined as the distance it takes for the boundary layers to completely merge together and for the flow to become fully developed. Entrance lengths for turbulent flows are shorter than that of laminar flows and are significantly affected by entrance conditions, intensity of any disturbances in the flow, and surface roughness. A widely used estimate for circular and noncircular ducts is