---
title: Internal Laminar Flow
---

# Couette Flow

Consider two parallel plates with infinite span separated by a constant density fluid of height $2b$. Each plate is a distance of $b$ away from the centerline. Neglect buoyancy effects and assume the top plate is moving at a constant velocity of $U$ while the bottom plate is stationary. Furthermore, assume the bottom and top plates are isothermal at temperatures of $T_s$ and $T_1$ respectively. The flow considered here is called **parallel flow** as all streamlines are parallel. Since all fluid elements move parallel to each other, $v=0$ and constant density mass conservation is

$$
\frac {\partial u}{\partial x}=-\frac {\partial v}{\partial y}=0
$$

Therefore, the velocity profile $u$ can *only* be a function of $y$. Assuming steady flow of a Newtonian fluid, the momentum equation in the $x$ and $y$ directions simplify to

$$
\begin{align*}
u\cancel{\frac {\partial u}{\partial x}}+\cancel{v\frac {\partial u}{\partial y}} & =-\frac 1{\rho}\cancel{\frac {\partial p}{\partial x}}+\nu\left(\cancel{\frac {\partial^2u}{\partial x^2}}+\frac {\partial^2u}{\partial y^2}\right) \\
u\cancel{\frac {\partial v}{\partial x}}+\cancel{v\frac {\partial v}{\partial y}} & =-\frac 1{\rho}\frac {\partial p}{\partial v}+\nu\left(\cancel{\frac {\partial^2v}{\partial x^2}}+\cancel{\frac {\partial^2v}{\partial y^2}}\right)
\end{align*}
$$

Momentum in the $y$ direction shows there is no pressure gradient in the $y$ direction. There also cannot be a pressure gradient in the $x$ direction as that would violate continuity. If we assumed $\frac {\partial p}{\partial x}\neq0$, then this would require $\frac {\partial^2u}{\partial x^2}\neq0$ so $u=u(x,y)$, which violates continuity. The PDE above reduces down to

$$
\frac {\mathrm d^2u}{\mathrm dy^2}=0
$$

subject to the boundary conditions $u(-b)=0$ and $u(b)=U$. Integrating twice to determine the velocity profile gives

$$
u(y)=\frac U2\left(1+\frac yb\right)
$$ {#eq-couette-flow-velocity-profile}

The energy equation for a constant density fluid is

$$
\rho C_p\left(u\cancel{\frac {\partial T}{\partial x}}+\cancel v\frac {\partial T}{\partial y}\right)=k\frac {\partial^2T}{\partial y^2}+\mu\left(\frac {\partial u}{\partial y}\right)^2
$$

# Poiseuille Flow