project:
  type: website
  resources:
    - "**/files**/*"
  output-dir: _site

website:
  title: Frank's Engineering Notebook
  bread-crumbs: false
  navbar:
    background: primary
    left:
      - text: Home
        href: index.qmd
      - text: Knowledge Base
        menu:
          - text: Fundamentals of Engineering
            href: knowledge-base/engineering-fundamentals/index.qmd
          - text: Propulsion Design
            href: knowledge-base/propulsion-design/index.qmd
      - text: Digital Notes
        href: notes/index.qmd
      - text: Projects
        href: projects/index.qmd
  sidebar:
    - id: engineering-fundamentals
      title: Fundamentals of Engineering
      style: floating
      collapse-level: 1
      contents:
        - section: Standards
          contents:
            - text: SAE AS4395 37&deg Flared Fitting
              href: knowledge-base/engineering-fundamentals/standards/sae-as4395-37deg-flared-fitting.qmd
        - section: CFD
          contents:
            - section: Computational Fluid Mechanics and Heat Transfer
              contents:
                - text: Chapter 2. Partial Differential Equations
                  href: knowledge-base/engineering-fundamentals/cfd/computational-fluid-mechanics-and-heat-transfer/chapters/chapter-2-partial-differential-equations.qmd
                - text: Chapter 4. Application of Numerical Methods to Model Equations
                  href: knowledge-base/engineering-fundamentals/cfd/computational-fluid-mechanics-and-heat-transfer/chapters/chapter-4-application-of-numerical-methods-to-model-equations.qmd
                - text: Chapter 6. Numerical Methods for Inviscid Flows
                  href: knowledge-base/engineering-fundamentals/cfd/computational-fluid-mechanics-and-heat-transfer/chapters/chapter-6-numerical-methods-for-inviscid-flows.qmd
                - text: Chapter 9. Numerical Methods for Navier-Stokes Equations
                  href: knowledge-base/engineering-fundamentals/cfd/computational-fluid-mechanics-and-heat-transfer/chapters/chapter-9-numerical-methods-for-navier-stokes-equations.qmd
            - text: Introduction to the AUSM Scheme
              href: knowledge-base/engineering-fundamentals/cfd/ausm-flux-splitting-scheme.qmd
        - section: Fluids
          contents:
            - section: Convective Heat and Mass Transfer
              contents:
                - text: Chapter 4. Internal Laminar Flow
                  href: knowledge-base/engineering-fundamentals/fluids/convective-heat-and-mass-transfer/chapters/chapter-4-internal-laminar-flow.qmd
                - text: Chapter 7. Turbulent and Transitional Internal Flow
                  href: knowledge-base/engineering-fundamentals/fluids/convective-heat-and-mass-transfer/chapters/chapter-7-turbulent-and-transitional-internal-flow.qmd
                - text: Chapter 8. Effects of Transpiration
                  href: knowledge-base/engineering-fundamentals/fluids/convective-heat-and-mass-transfer/chapters/chapter-8-effects-of-transpiration.qmd
                - text: Chapter 10. Natural Convection
                  href: knowledge-base/engineering-fundamentals/fluids/convective-heat-and-mass-transfer/chapters/chapter-10-natural-convection.qmd
            - section: Fundamentals of Heat and Mass Transfer
              contents:
                - text: Chapter 7. External Flow
                  href: knowledge-base/engineering-fundamentals/fluids/fundamentals-of-heat-and-mass-transfer/chapters/chapter-7-external-flow.qmd
            - text: Forced Flows Correlations
              href: knowledge-base/engineering-fundamentals/fluids/forced-flows-correlations.qmd
            - text: Free and Mixed Convection Correlations
              href: knowledge-base/engineering-fundamentals/fluids/free-mixed-convection-correlations.qmd
        - section: Structures
          contents:
            - section: Fundamentals of Metal Fatigue Analysis
              contents:
                - text: Chapter 5. Variable Amplitude Loading
                  href: knowledge-base/engineering-fundamentals/structures/fundamentals-of-metal-fatigue-analysis/chapters/chapter-5-variable-amplitude-loading.qmd
                - text: Chapter 7. Multiaxial Fatigue
                  href: knowledge-base/engineering-fundamentals/structures/fundamentals-of-metal-fatigue-analysis/chapters/chapter-7-multiaxial-fatigue.qmd
            - text: Limits and Fits
              href: knowledge-base/engineering-fundamentals/structures/limits-and-fits.qmd
    - id: propulsion-design
      title: Propulsion Design
      style: floating
      collapse-level: 1
      contents:
        - section: Injectors
          contents:
            - section: Pintle Injector
              contents:
                - text: Design Procedures for Moveable Pintle
                  href: knowledge-base/propulsion-design/injector/pintle/design-procedures-moveable-pintle.qmd
        - section: Sprays and Atomization
          contents:
            - text: Spray Dropsize Correlations
              href: knowledge-base/propulsion-design/sprays-and-atomization/spray-dropsize-correlations.qmd
            - text: Spray Impingement Simulation
              href: knowledge-base/propulsion-design/sprays-and-atomization/spray-impingement-simulation.qmd
format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 300px
      body-width: 1300px
      margin-width: 250px
      gutter-width: 1.5rem
    css: styles.css
    toc: true
    html-math-method: katex

crossref:
  eq-prefix: Eqn.
  eq-title: ""
  fig-prefix: Fig.
  sec-prefix: Sec.