project:
  output-dir: pdfs

format:
  pdf:
    toc: true
    callout-appearance: simple
    number-sections: true
    colorlinks: true
    papersize: a3
    classoption: portrait
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded