project:
  output-dir: pdfs

format:
  pdf:
    toc: true
    callout-appearance: simple
    number-sections: true
    colorlinks: true
    papersize: a4
    classoption: portrait
    geometry:
      - top=0.75in
      - bottom=.75in
      - left=.75in
      - right=.75in
      - heightrounded
    include-in-header:
      - text: |
          \usepackage{cancel}